### ISSUE TITLE
year moving to 2021 causing all torrents to be deleted?

### ISSUE THREAD

**Issue by BinsonBuzz** [Hundter/qBittorrent-Ratio-Manager#10]
happy new year!

Suddenly today (2nd) all my torrents are being deleted.  I think the seeding time isn't being honoured as the year moved onto to 2021 and only the `"min_seed_time": 24` is being honoured - why all my torrents disappeared on the 2nd.

Anyone else having problems?

**Comment by Hundter** [comment]
Happy new year,

qBittorrent Ratio Manager does not calculate time seeded itself, but relies on the time seeded provided by the qBittorrent API. So if there was a problem due to the year change it would be on the qBittorrent API. My qBittorrent still seems to provide accurate values, however, and I haven't had any mass deletion problems. Can you try posting the rest of your config? (min_seed_ratio/max_seed_ratio/max_seed_time)

**Comment by BinsonBuzz** [comment]
Here you go. I tried changing the min_seed_time to 360 as well, but it still deleted new torrents I added.  It was working fine for months until yesterday

```
{
    "category": "imported",
    "tracker": "ssl.empirehost.me",
    "public": {
        "min_seed_ratio": 1.1,
        "max_seed_ratio": 2000,
        "min_seed_time": 24,
        "max_seed_time": 360,
        "required_seeders": 0
    },
	"private": {
        "min_seed_ratio": 1.1,
        "max_seed_ratio": 2000,
        "min_seed_time": 24,
        "max_seed_time": 360,
        "required_seeders": 0
    },
	"delete_files": true
}
```

**Comment by Hundter** [comment]
Have you tried only running ratio manager manually and verified that it IS indeed ratio manager that is deleting the torrents? Also what version are you running? Perhaps an older of version of qBittorrent had a bug with year changes.

**Comment by BinsonBuzz** [comment]
hmm I just ran manually and my torrents weren't deleted.  Looks like a false alarm, but I can't think of anything I changed that would delete my torrents.

Sorry!

**Comment by Hundter** [comment]
No problem, don't hesitate to reopen the issue if ratio manager keeps causing problems :)
