### ISSUE TITLE
Feature request: wildcard category

### ISSUE THREAD

**Issue by bjeanes** [Hundter/qBittorrent-Ratio-Manager#8]
I use a lot of categories that I don't want to hardcode in qman and don't vary in requirements. It'd be convenient if there was allowed to be at-most one `.qman` file with category set to something like `*`, or without category specified, that would be applied to all categories that do not have specific configuration.

**Comment by Hundter** [comment]
I changed around the functionality a bit so that this could be supported. Using "*" as the category now affects all categories that don't have a specific .qman already (also uncategorized torrents). If you want to specify rules for uncategorized torrents you can use an empty string "" as the category :)

**Comment by bjeanes** [comment]
Awesome! Thanks :)
